---
- name: Common | Set hostname
  hostname: name={{ server_hostname }}
  sudo: yes
  tags: common

- name: Common | Update apt cache
  sudo: yes
  apt: update-cache=yes
  tags: common

- name: Common | Update language
  sudo: yes
  apt: pkg=language-pack-en
  tags: common
